locale          : "en-US"
site_theme      : "default"
title           : "Santiago Cantillo-Cleves"
title_separator : "-"
name            : "Santiago Cantillo-Cleves"
description     : "PhD Candidate in Economics at UC San Diego researching public, labor, and urban economics."
url             : "https://SantiagoCantilloCleves.github.io"
baseurl         : ""
repository      : "https://SantiagoCantilloCleves.github.io"

author:
  avatar   : "profile.png"
  name     : "Santiago Cantillo-Cleves"
  bio      : "Economics PhD Candidate"
  location : "UC San Diego"
  cv       : "https://www.dropbox.com/scl/fi/jfv6e3izpj7gnfuwz9meo/CV_CantilloCleves.pdf?rlkey=yjrtevv9g3v4lsf0mqd35205c&dl=0"
  email    : "santiago@ucsd.edu"
  github   : "SantiagoCantilloCleves"
  scholar  : "https://scholar.google.com/citations?user=_00qL3EAAAAJ&hl=en"

include:
  - _pages

exclude:
  - .bundle
  - .github
  - CONTRIBUTING.md
  - Dockerfile
  - Gemfile
  - LICENSE
  - README
  - docker-compose.yaml
  - vendor

encoding: "utf-8"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
